"""empty message

Revision ID: 206bb17ed8cf
Revises: 8933e1ba5f5f
Create Date: 2022-08-05 17:22:31.045797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206bb17ed8cf'
down_revision = '8933e1ba5f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotations', sa.Column('quote_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotations', 'quote_date')
    # ### end Alembic commands ###
