"""empty message

Revision ID: 95aba7a341ee
Revises: 206bb17ed8cf
Create Date: 2022-08-05 21:45:21.220642

"""
import sqlalchemy as sa
from alembic import op

from app.configs.pupulate_is_external_currencies_column import (
    pupulate_is_external_currencies_column,
)

# revision identifiers, used by Alembic.
revision = "95aba7a341ee"
down_revision = "206bb17ed8cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("currencies", sa.Column("is_external", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    pupulate_is_external_currencies_column()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("currencies", "is_external")
    # ### end Alembic commands ###
